//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMalUpdaterDatalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string EnglishTitle { get; set; }
        public string Synonyms { get; set; }
        public Nullable<int> Episodes { get; set; }
        public Nullable<double> Score { get; set; }
        public string AnimeType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Synopsis { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> SynopsisFileLastGenerated { get; set; }
        public Nullable<System.DateTime> DataUpdatedDate { get; set; }
    }
}
